"""
Django settings for paw_meet project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import decouple
from pathlib import Path
from django.conf.locale.es import formats as es_formats
from django.utils.translation import gettext_lazy as _
from datetime import timedelta
from celery.schedules import crontab
import os

# ___________________________________
# CELERY
# ___________________________________

CELERY_BROKER_URL = 'amqp://paw_meet:paw_meet@rabbitmq:5672//'

CELERY_CACHE_BACKEND = 'default'

# Serialización
CELERY_ACCEPT_CONTENT   = ['json']
CELERY_TASK_SERIALIZER  = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Configuración programada de las tareas a ejecutar por CELERY
CELERY_BEAT_SCHEDULE = {
    'actualizar_estado_eliminado' : {
        'task' : 'encuentros.tasks.actualizar_estado_eliminado',
        'schedule' : crontab(minute = '*/15')
    },
    'actualizar_encuentros_programados' : {
        'task' : 'encuentros.tasks.actualizar_encuentros_programados',
        'schedule' : crontab(minute = '*/15')
    }
}

CELERY_TIMEZONE = 'Europe/Madrid'
CELERY_ENABLE_UTC = True

# Formatos de conversión y entradas sobre fechas
es_formats.DATETIME_FORMAT = "d M Y H:i"
es_formats.DATE_FORMAT = "d/m/Y"
es_formats.DATE_INPUT_FORMATS = ["%d/%m/%Y",]
es_formats.DATETIME_INPUT_FORMATS = ["%d/%m/%Y %H:%M",]

# ___________________________________
# OUTLOOK - EMAIL
# ___________________________________
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = decouple.config('EMAIL_PORT')
EMAIL_USE_TLS = decouple.config('EMAIL_TLS')
EMAIL_HOST_USER = decouple.config('EMAIL_USER')
EMAIL_HOST_PASSWORD = decouple.config('EMAIL_PASSWORD')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = decouple.config('SECRET_KEY', default = "Cambiar_en_produccion")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = decouple.config('DEBUG', default = True, cast=bool)

ALLOWED_HOSTS = decouple.config('ALLOWED_HOSTS', default = '127.0.0.1, localhost', cast=lambda v: [s.strip() for s in v.split(',')]) # Obtiene todos los hosts permitidos que se encuentran separados por ','

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',

    'users',
    'encuentros',
    'django_celery_results',
    'django_celery_beat',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN' # Método de prevención contra ataques ClickJacking

ROOT_URLCONF = 'paw_meet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'paw_meet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if decouple.config('DB_TYPE', default="sqlite") == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': decouple.config('POSTGRES_DB', default='postgres'),
            'USER': decouple.config('POSTGRES_USER', default='postgres'),
            'PASSWORD': decouple.config('POSTGRES_PASSWORD', default='postgres'),
            'HOST': decouple.config('POSTGRES_HOST', default='db'),
            #'HOST': 'localhost',
            #'PORT': '25432',
            'PORT': decouple.config('POSTGRES_PORT', default='5432'),
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ── JWT ───────────────────────────────────────
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True, 
    'UPDATE_LAST_LOGIN': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
]

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

AUTH_USER_MODEL = 'users.CustomUser'

SITE_ID = 1

PASSWORD_RESET_TIMEOUT = 3600

PAGINATION_COUNT = 5

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Paw-Meet API',
    'DESCRIPTION': 'API para la red social Paw-Meet. Protegida mediante JWT Bearer.',
    'VERSION': '1.0.0',
    'COMPONENT_SPLIT_REQUEST': True
}

CSRF_TRUSTED_ORIGINS = decouple.config('CSRF_TRUSTED_ORIGINS', default='http://127.0.0.1, http://localhost', cast=lambda v: [s.strip() for s in v.split(',')])
CORS_ALLOWED_ORIGINS = decouple.config('CSRF_TRUSTED_ORIGINS', default='http://127.0.0.1, http://localhost', cast=lambda v: [s.strip() for s in v.split(',')])
CORS_ALLOW_ALL_ORIGINS = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}
