services:
  postgres:
    container_name: pawmeet_db
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pawmeet_db
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  pawmeet:
    image: mendo1/paw_meet_backend:1.0
    container_name: django_pawmeet
    restart: always
    env_file:
      - ./paw_meet/.env
    depends_on:
      - postgres
    profiles:
      - produccion
    ports: 
      - "8003:8000"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: paw_meet
      RABBITMQ_DEFAULT_PASS: paw_meet
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
  
  beat:
    build: .
    container_name: celery_beat
    command: python -m celery -A paw_meet beat --loglevel=info
    restart: always
    env_file:
      - ./paw_meet/.env
    environment:
      - DJANGO_SETTINGS_MODULE=paw_meet.settings
      - CELERY_BROKER_URL=amqp://paw_meet:paw_meet@rabbitmq:5672//
      - PYTHONPATH=/app
    depends_on:
      - postgres
      - rabbitmq
      - worker
      
  worker:
    build: .
    container_name: celery_worker
    command: python -m celery -A paw_meet worker --loglevel=info
    restart: always
    env_file:
      - ./paw_meet/.env
    environment:
      - DJANGO_SETTINGS_MODULE=paw_meet.settings
      - CELERY_BROKER_URL=amqp://paw_meet:paw_meet@rabbitmq:5672//
      - PYTHONPATH=/app
    depends_on:
      - postgres
      - rabbitmq

  pawmeet_develop:
    build: .
    container_name: django_pawmeet_develop
    restart: always
    volumes:
      - ./paw_meet:/app/paw_meet
    env_file:
      - ./paw_meet/.env
    depends_on:
      - postgres
    ports:
      - "8004:8000"
    profiles:
      - desarrollo
    expose:
      - 8000
    working_dir: /app/paw_meet 
    command: python manage.py runserver 0.0.0.0:8000

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local 