services:
  postgres:
    container_name: pawmeet_db
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pawmeet_db
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  pawmeet:
    build: .
    container_name: django_pawmeet
    restart: always
    volumes:
      - ./paw_meet:/app
    env_file:
      - ./paw_meet/.env
    depends_on:
      - postgres
    ports:
      - "8003:8000"
    profiles:
      - app
    expose:
      - 8000

volumes:
  postgres_data:
  pgadmin_data:  