# Generated by Django 6.0.3 on 2026-04-14 08:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_customuser_options_pettype_alter_pet_pet_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contador_usuarios', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Al registrar una asistencia, no se puede superar el límite de usuarios establecido en el encuentro.')])),
                ('contador_mascotas', models.IntegerField(default=0)),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
            },
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('localizacion', models.CharField(default='', help_text='Ciudad o zona donde se realizará el encuentro.', max_length=150)),
                ('limite_usuarios', models.IntegerField(default=2, help_text='Número máximo de usuarios que pueden asistir al encuentro.', validators=[django.core.validators.MaxValueValidator(limit_value=10, message='No se puede incluir un límite superior a 10')])),
                ('duracion_minutos', models.IntegerField(default=15, help_text='Número de minutos que va a durar el encuentro.º', validators=[django.core.validators.MaxValueValidator(limit_value=120, message='No puede durar el encuentro más de 2 horas')])),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción del encuentro formalizado.', max_length=300)),
                ('titulo', models.CharField(default='Prueba Encuentro', help_text='Título asociado al encuentro formalizado.', max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('pendiente', 'Pendiente'), ('eliminado', 'Eliminado')], default='', help_text='Estado actual del encuentro formalizado.', max_length=30)),
                ('asistencia', models.ForeignKey(blank=True, help_text='Asistencias registradas para el encuentro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_de_encuentro', to='encuentros.asistencia')),
                ('tipo_mascota', models.ManyToManyField(to='users.pettype')),
            ],
            options={
                'verbose_name': 'encuentro',
                'verbose_name_plural': 'encuentros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='encuentro',
            field=models.ForeignKey(blank=True, help_text='Asistencias registradas para el encuentro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_de_encuentro', to='encuentros.encuentro'),
        ),
    ]
