# Generated by Django 6.0.3 on 2026-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('pendiente', 'Pendiente'), ('eliminado', 'Eliminado')], default='', help_text='Estado actual del encuentro formalizado.', max_length=30),
        ),
    ]
