# Generated by Django 6.0.3 on 2026-04-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0003_encuentro_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('eliminado', 'Eliminado')], default='', help_text='Estado actual del encuentro formalizado.', max_length=30),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='estado',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('eliminado', 'Eliminado')], default='', help_text='Estado actual del encuentro formalizado.', max_length=30),
        ),
    ]
