# Generated by Django 6.0.3 on 2026-04-16 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0004_alter_asistencia_estado_alter_encuentro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='fecha_realizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
