# Generated by Django 6.0.3 on 2026-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0005_encuentro_fecha_realizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('finalizado', 'Finalizado'), ('programado', 'Programado'), ('eliminado', 'Eliminado')], default='', help_text='Estado actual del encuentro formalizado.', max_length=30),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='estado',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('finalizado', 'Finalizado'), ('programado', 'Programado'), ('eliminado', 'Eliminado')], default='', help_text='Estado actual del encuentro formalizado.', max_length=30),
        ),
    ]
