# Generated by Django 6.0.3 on 2026-04-23 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0006_alter_asistencia_estado_alter_encuentro_estado'),
        ('users', '0006_alter_pettype_codigo_alter_pettype_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='tipo_mascota',
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='Dirección o punto de encuentro específico', max_length=255)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud para geolocalización', max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud para geolocalización', max_digits=9, null=True)),
                ('date', models.DateField(help_text='Fecha del encuentro')),
                ('start_time', models.TimeField(help_text='Hora de inicio')),
                ('end_time', models.TimeField(help_text='Hora de finalización')),
                ('max_participants', models.PositiveIntegerField(default=10, help_text='Número máximo de participantes (incluye al creador)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('ongoing', 'En curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='encuentros.city')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('pets', models.ManyToManyField(blank=True, related_name='meetings', to='users.pet')),
            ],
            options={
                'verbose_name': 'Encuentro',
                'verbose_name_plural': 'Encuentros',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('attended', 'Asistió'), ('no_show', 'No asistió')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del asistente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pets', models.ManyToManyField(blank=True, help_text='Mascotas que trae el usuario a este encuentro', related_name='attendances', to='users.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='encuentros.meeting')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='Encuentro',
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'status'], name='encuentros__date_6dedc9_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['city', 'date'], name='encuentros__city_id_c985c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('meeting', 'user')},
        ),
    ]
