# Generated by Django 6.0.3 on 2026-05-01 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0007_city_remove_encuentro_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Punto espacial generado automáticamente', null=True, srid=4326),
        ),
    ]
