# Generated by Django 6.0.3 on 2026-04-13 17:13

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('admin', 'Administrador')], default='user', max_length=10)),
                ('bio', models.TextField(blank=True, default='', help_text='Descripción personal del usuario. Máx. 500 caracteres recomendados.', validators=[django.core.validators.MinLengthValidator(0)])),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil del usuario.', null=True, upload_to='media/users/%Y/%m')),
                ('phone', models.CharField(blank=True, default='', help_text='Teléfono de contacto opcional', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.ciudad')),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': ('Usuarios',),
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('rabbit', 'Conejo'), ('bird', 'Pájaro'), ('reptile', 'Reptil'), ('rodent', 'Roedor'), ('other', 'Otro')], default='dog', max_length=20)),
                ('species', models.CharField(blank=True, default='', help_text="Especie libre (rellenar solo si tipo es 'Otro').", max_length=100)),
                ('breed', models.CharField(blank=True, default='', help_text='Raza de la mascota.', max_length=100)),
                ('size', models.CharField(blank=True, choices=[('small', 'Pequeño (< 10kg)'), ('medium', 'Mediano (10-25kg)'), ('large', 'Grande (> 25kg)')], default='', help_text='Tamaño aproximado. Especialmente relevante para perros.', max_length=10)),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento. Permite calcular edad en la API.', null=True)),
                ('bio', models.TextField(blank=True, default='', help_text='Descripción de la mascota: carácter, gustos, etc.')),
                ('avatar', models.ImageField(blank=True, help_text='Foto de la mascota.', null=True, upload_to='media/mascotas/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text="Permite 'archivar' mascotas sin eliminarlas (fallecidas, etc.).")),
                ('owner', models.ForeignKey(help_text='Dueño registrado de la mascota.', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_pet_name_per_owner')],
            },
        ),
    ]
