# Generated by Django 6.0.3 on 2026-04-14 08:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_ciudad_delete_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('codigo', models.CharField(default='', max_length=8, validators=[django.core.validators.ProhibitNullCharactersValidator])),
            ],
            options={
                'verbose_name': 'pet_type',
                'verbose_name_plural': 'pets_type',
                'ordering': ['-codigo'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'codigo'), name='unique_pet_types')],
            },
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(help_text='Tipo de mascota registrada.', on_delete=django.db.models.deletion.CASCADE, related_name='pets_type', to='users.pettype'),
        ),
    ]
