# Generated by Django 6.0.3 on 2026-04-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0002_asistencia_estado'),
        ('users', '0003_alter_customuser_options_pettype_alter_pet_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encuentros',
            field=models.ForeignKey(blank=True, help_text='Encuentros registrados por el usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuentros_creados', to='encuentros.encuentro'),
        ),
    ]
