# Generated by Django 6.0.3 on 2026-04-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_encuentros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='encuentros',
        ),
    ]
