# Generated by Django 6.0.3 on 2026-04-22 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_encuentros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettype',
            name='codigo',
            field=models.CharField(default='PERROS', max_length=8, validators=[django.core.validators.ProhibitNullCharactersValidator]),
        ),
        migrations.AlterField(
            model_name='pettype',
            name='nombre',
            field=models.CharField(default='Beagle', max_length=100),
        ),
    ]
