# Generated by Django 6.0.3 on 2026-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_pettype_codigo_alter_pettype_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
