# Generated by Django 6.0.3 on 2026-05-01 16:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_supabase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud para geolocalización', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud para geolocalización', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Punto espacial generado automáticamente', null=True, srid=4326),
        ),
    ]
