# Generated by Django 6.0.3 on 2026-05-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_location_lat_customuser_location_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location_point',
        ),
    ]
