# Generated by Django 6.0.3 on 2026-05-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0008_meeting_location_point'),
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='encuento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuentros.meeting'),
        ),
    ]
