# Generated by Django 6.0.3 on 2026-05-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0002_foro_encuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foro',
            old_name='encuento',
            new_name='encuentro',
        ),
    ]
